Test Windows builds using Appveyor (#46)
* Add Appveyor config

* Disabling GNU toolchain

Build using GNU toolchain fails while compiling rust-crypto crate:

    Running `C:\projects\aerospike-client-rust-1w5vx\target\debug\build\rust-crypto-870e4870d730b0b2\build-script-build`
    error: failed to run custom build command for `rust-crypto v0.2.36`
    process didn't exit successfully: `C:\projects\aerospike-client-rust-1w5vx\target\debug\build\rust-crypto-870e4870d730b0b2\build-script-build` (exit code: 101)
    --- stdout
    TARGET = Some("x86_64-pc-windows-gnu")
    OPT_LEVEL = Some("0")
    TARGET = Some("x86_64-pc-windows-gnu")
    TARGET = Some("x86_64-pc-windows-gnu")
    HOST = Some("x86_64-pc-windows-gnu")
    CFLAGS_x86_64-pc-windows-gnu = None
    CFLAGS_x86_64_pc_windows_gnu = None
    HOST_CFLAGS = None
    CFLAGS = None
    DEBUG = Some("true")
    running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-g" "-m64" "-Wall" "-Wextra" "-o" "C:\\projects\\aerospike-client-rust-1w5vx\\target\\debug\\build\\rust-crypto-b1b8a44f96d5ded8\\out\\src\\util_helpers.o" "-c" "src/util_helpers.c"
    --- stderr
    thread 'main' panicked at '
    Internal error occurred: Failed to find tool. Is `cc` installed? (see https://github.com/alexcrichton/gcc-rs#compile-time-requirements for help)
    ', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\gcc-0.3.54\src\lib.rs:1670:4

* Switch to VS 2017 image

VS 2017 image includes Docker support
https://www.appveyor.com/docs/build-environment/#docker

* Test: check out docker version installed on build image

* Try to run aerospike-server docker image

* Revert change to start aerospike-server container

Windows Server 2016 docker server on VS 2017 build image does not
support running Linux containers out of the box:

    docker version
    Client:
     Version:      17.06.1-ee-2
     API version:  1.30
     Go version:   go1.8.3
     Git commit:   8e43158
     Built:        Wed Aug 23 21:16:53 2017
     OS/Arch:      windows/amd64
    Server:
     Version:      17.06.1-ee-2
     API version:  1.30 (minimum version 1.24)
     Go version:   go1.8.3
     Git commit:   8e43158
     Built:        Wed Aug 23 21:25:53 2017
     OS/Arch:      windows/amd64
     Experimental: false

    docker run -tid --name aerospike -p 3000:3000 -p 3001:3001 -p 3002:3002 -p 3003:3003 aerospike/aerospike-server
    Unable to find image 'aerospike/aerospike-server:latest' locally
    latest: Pulling from aerospike/aerospike-server
    docker: image operating system "linux" cannot be used on this platform.
    See 'docker run --help'.
    Command exited with code 125

* Rename appveyor config file

* Just run the unit tests (--lib) for now

* Enable backtraces for errors while running tests