Update Travis build env from Trusty to Xenial
Aerospike server v4.7 requires a newer version of libstdc++6 than ships
with Ubuntu 14.04 (aka Trusty):

    $ .travis/start_cluster.sh 2
    2019-11-13 12:25:00 URL:https://aerospike.com/artifacts/aerospike-server-community/4.7.0.3/aerospike-server-community-4.7.0.3.tar.gz [7532001/7532001] -> "aerospike-server.tgz" [1]
    error: start failed due to an error.
    /home/travis/build/aerospike/aerospike-client-rust/aerospike-server/instance1/bin/asd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/build/aerospike/aerospike-client-rust/aerospike-server/instance1/bin/asd)